In [56]:
size_of_vec = 100000000

In [51]:
import time
def pure_python_version():
    start_time = time.time()
    list1 = range(size_of_vec)
    list2 = range(size_of_vec)
    sum_list = [list1[i] + list2[i] for i in range(size_of_vec)]
    return time.time() - start_time

In [52]:
import numpy as np

def numpy_version():
    start_time = time.time()
    list1 = np.arange(size_of_vec)
    list2 = np.arange(size_of_vec)
    sum_list = list1 + list2
    return time.time() - start_time

In [57]:
python_time = pure_python_version()
numpy_time = numpy_version()
print("Pure python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is {0} times faster than Pure python".format(python_time/numpy_time))

Pure python version 23.3586
Numpy version 1.1485
Numpy is 20.33822816584527 times faster than Pure python


In [58]:
arr = np.array([1,2,3,4,5])
type(arr)


numpy.ndarray

In [69]:
my_mat = [[1,2,3,10],[4,5,6,11],[7,8,9,12]]
type(my_mat)

list

In [70]:
mat = np.array(my_mat)
mat


array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [73]:
arr.shape

(5,)

In [75]:
arr.ndim

1

In [74]:
mat.shape

(3, 4)

In [76]:
mat.ndim

2

In [77]:
mat.dtype

dtype('int64')

In [84]:
np.arange(1,11,2, dtype=int)

array([1, 3, 5, 7, 9])

In [91]:
np.zeros((3,4), dtype=float, order = 'C')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
linsparr = np.linspace(2.1, 5.5)
print(linsparr[3]-linsparr[2])
print(linsparr[2]-linsparr[1])

0.06938775510204076
0.06938775510204076


TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [105]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [129]:
num = np.random.randn(10)
sum(num)

4.522751055756199

In [140]:
np.random.random(16).reshape(8,2)


array([[0.76061884, 0.25158576],
       [0.51779436, 0.38863529],
       [0.3086729 , 0.15493615],
       [0.71753874, 0.4405746 ],
       [0.42455333, 0.6425151 ],
       [0.60599272, 0.00645511],
       [0.65793009, 0.12685155],
       [0.26355776, 0.46241221]])

In [148]:
mat = np.random.rand(5,6)
print(mat)
print(mat[2:4,1:3])
print(mat[2:, 2:])

[[0.89632553 0.42625765 0.75542213 0.76612126 0.02137928 0.2802533 ]
 [0.79293722 0.81732481 0.83070739 0.57690735 0.77999626 0.02305524]
 [0.21507329 0.81196239 0.35750701 0.13790061 0.23047554 0.06300833]
 [0.31953481 0.15955895 0.22945356 0.86233726 0.31004256 0.3484382 ]
 [0.66366254 0.64622513 0.73560669 0.99210751 0.84384437 0.13051314]]
[[0.81196239 0.35750701]
 [0.15955895 0.22945356]]
[[0.35750701 0.13790061 0.23047554 0.06300833]
 [0.22945356 0.86233726 0.31004256 0.3484382 ]
 [0.73560669 0.99210751 0.84384437 0.13051314]]


In [154]:
arr_cond = np.arange(10)
arr_cond[(arr_cond>5) & (arr_cond<8)]

array([6, 7])

In [161]:
scalar = 7
arr_1d = np.array([10,10,10])
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
arr_1d + arr_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [172]:
arr = np.random.rand(10)
print(arr)
exp_arr = np.exp(arr)
np.log(exp_arr)

[0.83101108 0.31365096 0.80698945 0.01590521 0.49052936 0.46109086
 0.46707116 0.14020141 0.14730886 0.64511205]


array([0.83101108, 0.31365096, 0.80698945, 0.01590521, 0.49052936,
       0.46109086, 0.46707116, 0.14020141, 0.14730886, 0.64511205])

In [167]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [171]:
import math
math.e
math.pow(math.e,0.29159323)

1.3385584214750086

In [178]:
arr_x = np.array([[1,2,3,4],
                  [5,6,7,8]])
arr_y = np.array([[21,22,23,24],
                  [25,26,27,28]])
arr_x + arr_y
print(np.concatenate((arr_x, arr_y), axis=0))
print(np.concatenate((arr_x, arr_y), axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]
[[ 1  2  3  4 21 22 23 24]
 [ 5  6  7  8 25 26 27 28]]


In [187]:
arr_z = np.concatenate((arr_x, arr_y), axis=0)
print(arr_z)
hsplits = np.hsplit(arr_z, 4)
print(np.array(hsplits))
vsplits = np.vsplit(arr_z,2)
print(np.array(vsplits))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]
[[[ 1]
  [ 5]
  [21]
  [25]]

 [[ 2]
  [ 6]
  [22]
  [26]]

 [[ 3]
  [ 7]
  [23]
  [27]]

 [[ 4]
  [ 8]
  [24]
  [28]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[21 22 23 24]
  [25 26 27 28]]]


In [188]:
import numpy as np

countries = ['India', 'France', 'England']
capitals = ['New Delhi', 'Paris', 'London']
arr = np.array(capitals)

In [189]:
import pandas as pd

In [190]:
pd.Series(data = capitals)

0    New Delhi
1        Paris
2       London
dtype: object

In [191]:
pd.Series(data = capitals, index=countries)

India      New Delhi
France         Paris
England       London
dtype: object

In [192]:
pd.Series(arr)

0    New Delhi
1        Paris
2       London
dtype: object

In [193]:
dicts = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80}

pd.Series(dicts)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64

In [274]:
dicts1 = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80}
dicts2 = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70}
s1 = pd.Series(dicts1)
s2 = pd.Series(dicts2)
s1+s2

a     20.0
b     40.0
c     60.0
d     80.0
e    100.0
f    120.0
g    140.0
h      NaN
dtype: float64

In [194]:
my_series = pd.Series(dicts)

In [195]:
my_series.shape

(8,)

In [196]:
my_series[0]

10

In [197]:
my_series['a']

10

In [198]:
my_series[1:3]

b    20
c    30
dtype: int64

In [200]:
my_series[[True,False,True,False,True,False,True,False]]

a    10
c    30
e    50
g    70
dtype: int64

In [202]:
my_series[['a','c','c']]

a    10
c    30
c    30
dtype: int64

In [203]:
my_series + my_series

a     20
b     40
c     60
d     80
e    100
f    120
g    140
h    160
dtype: int64

In [206]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [207]:
fruits = ['Apple', 'Banana', 'Orange']
fruits_df = pd.DataFrame(data = fruits, columns=['Fruit'])
fruits_df

Fruit
0   Apple
1  Banana
2  Orange

In [208]:
family = [['Suyash', 32, 'Father'],['Abha', 32, 'Mother'],['Atharv', 3, 'Son']]
family_df = pd.DataFrame(data = family, columns=['Name', 'Age', 'Role'])
family_df

Name  Age    Role
0  Suyash   32  Father
1    Abha   32  Mother
2  Atharv    3     Son

In [214]:
family = {'Name':['Suyash', 'Abha', 'Atharv'], 'Age':[32,32,3], 'Role':["Father", "Mother", "Son"]}
family_df = pd.DataFrame(data = family)
family_df

Name  Age    Role
0  Suyash   32  Father
1    Abha   32  Mother
2  Atharv    3     Son

In [215]:
csv_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.csv")
csv_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [217]:
json_df = pd.read_json("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.json")
json_df

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [218]:
excel_df = pd.read_excel("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.xlsx?raw=true", sheet_name=0)
excel_df

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [219]:
employee_df = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/Employee%20data.csv'

Gender  Employee Number           Skills  Total Working Years  \
0  Female                1            Sales                    8   
1  Female                5         Research                    8   
2  Female               10  Content Writing                   12   
3  Female               15  Content Writing                   10   
4  Female               20            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [220]:
employee_df.shape

(1470, 9)

In [224]:
employee_df.dtypes

Gender                      object
Employee Number              int64
Skills                      object
Total Working Years          int64
Work Life Balance            int64
Performance Rating           int64
Years At Company             int64
MonthlyIncome(June-2018)     int64
MonthlyIncome(June-2017)     int64
dtype: object

In [225]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 9 columns):
Gender                      1470 non-null object
Employee Number             1470 non-null int64
Skills                      1470 non-null object
Total Working Years         1470 non-null int64
Work Life Balance           1470 non-null int64
Performance Rating          1470 non-null int64
Years At Company            1470 non-null int64
MonthlyIncome(June-2018)    1470 non-null int64
MonthlyIncome(June-2017)    1470 non-null int64
dtypes: int64(7), object(2)
memory usage: 103.4+ KB


In [226]:
employee_df.count()

Gender                      1470
Employee Number             1470
Skills                      1470
Total Working Years         1470
Work Life Balance           1470
Performance Rating          1470
Years At Company            1470
MonthlyIncome(June-2018)    1470
MonthlyIncome(June-2017)    1470
dtype: int64

In [230]:
employee_df.index

RangeIndex(start=0, stop=1470, step=1)

In [231]:
employee_df.head()

Gender  Employee Number           Skills  Total Working Years  \
0  Female                1            Sales                    8   
1  Female                5         Research                    8   
2  Female               10  Content Writing                   12   
3  Female               15  Content Writing                   10   
4  Female               20            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [244]:
new_df = employee_df.set_index('Employee Number')

In [250]:
new_df.reset_index(inplace=True)

In [251]:
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [265]:
new_df['Name'] = ['Anonymous' for i in range(new_df.shape[0])]

In [267]:
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)       Name  
0                      5993                      5893  Anonymous  
1                      5130                      4000  Anonymous  
2                      2090                      3050  Anonymous  
3                      2909                      5909  Anonymous  
4                      3468                      2468  Anonymous

In [268]:
new_df['Years Outside Company'] = new_df['Total Working Years'] - new_df['Years At Company']
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)       Name  \
0                      5993                      5893  Anonymous   
1                      5130                      4000  Anonymous   
2                      2090                      3050  Anonymous   
3                      2909                      5909  Anonymous   
4                      3468                      2468  Anonymous   

   Years Outside Company  
0                      2  
1                      0  
2                     11  
3                      1  
4                      0

In [270]:
new_df.drop(labels='Name', axis=1).head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  Years Outside Company  
0                      5993                      5893                      2  
1                      5130                      4000                      0  
2                      2090                      3050                     11  
3                      2909                      5909                      1  
4                      3468                      2468                      0

In [ ]:
new_df.drop(labels='')

In [271]:
dicts = {1:'Ram', 2:'Shyam', 3:'Ghanshyam'}
mydf = pd.Series(data=dicts)
mydf


1          Ram
2        Shyam
3    Ghanshyam
dtype: object

In [273]:
mydf[1]

'Ram'