In [56]:
size_of_vec = 100000000

In [51]:
import time
def pure_python_version():
    start_time = time.time()
    list1 = range(size_of_vec)
    list2 = range(size_of_vec)
    sum_list = [list1[i] + list2[i] for i in range(size_of_vec)]
    return time.time() - start_time

In [52]:
import numpy as np

def numpy_version():
    start_time = time.time()
    list1 = np.arange(size_of_vec)
    list2 = np.arange(size_of_vec)
    sum_list = list1 + list2
    return time.time() - start_time

In [57]:
python_time = pure_python_version()
numpy_time = numpy_version()
print("Pure python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is {0} times faster than Pure python".format(python_time/numpy_time))

Pure python version 23.3586
Numpy version 1.1485
Numpy is 20.33822816584527 times faster than Pure python


In [58]:
arr = np.array([1,2,3,4,5])
type(arr)


numpy.ndarray

In [69]:
my_mat = [[1,2,3,10],[4,5,6,11],[7,8,9,12]]
type(my_mat)

list

In [70]:
mat = np.array(my_mat)
mat


array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [73]:
arr.shape

(5,)

In [75]:
arr.ndim

1

In [74]:
mat.shape

(3, 4)

In [76]:
mat.ndim

2

In [77]:
mat.dtype

dtype('int64')

In [84]:
np.arange(1,11,2, dtype=int)

array([1, 3, 5, 7, 9])

In [91]:
np.zeros((3,4), dtype=float, order = 'C')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [96]:
linsparr = np.linspace(2.1, 5.5)
print(linsparr[3]-linsparr[2])
print(linsparr[2]-linsparr[1])

0.06938775510204076
0.06938775510204076


TypeError: unsupported operand type(s) for /: 'str' and 'int'

In [105]:
np.eye(3,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [129]:
num = np.random.randn(10)
sum(num)

4.522751055756199

In [140]:
np.random.random(16).reshape(8,2)


array([[0.76061884, 0.25158576],
       [0.51779436, 0.38863529],
       [0.3086729 , 0.15493615],
       [0.71753874, 0.4405746 ],
       [0.42455333, 0.6425151 ],
       [0.60599272, 0.00645511],
       [0.65793009, 0.12685155],
       [0.26355776, 0.46241221]])

In [148]:
mat = np.random.rand(5,6)
print(mat)
print(mat[2:4,1:3])
print(mat[2:, 2:])

[[0.89632553 0.42625765 0.75542213 0.76612126 0.02137928 0.2802533 ]
 [0.79293722 0.81732481 0.83070739 0.57690735 0.77999626 0.02305524]
 [0.21507329 0.81196239 0.35750701 0.13790061 0.23047554 0.06300833]
 [0.31953481 0.15955895 0.22945356 0.86233726 0.31004256 0.3484382 ]
 [0.66366254 0.64622513 0.73560669 0.99210751 0.84384437 0.13051314]]
[[0.81196239 0.35750701]
 [0.15955895 0.22945356]]
[[0.35750701 0.13790061 0.23047554 0.06300833]
 [0.22945356 0.86233726 0.31004256 0.3484382 ]
 [0.73560669 0.99210751 0.84384437 0.13051314]]


In [154]:
arr_cond = np.arange(10)
arr_cond[(arr_cond>5) & (arr_cond<8)]

array([6, 7])

In [161]:
scalar = 7
arr_1d = np.array([10,10,10])
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
arr_1d + arr_2d

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [172]:
arr = np.random.rand(10)
print(arr)
exp_arr = np.exp(arr)
np.log(exp_arr)

[0.83101108 0.31365096 0.80698945 0.01590521 0.49052936 0.46109086
 0.46707116 0.14020141 0.14730886 0.64511205]


array([0.83101108, 0.31365096, 0.80698945, 0.01590521, 0.49052936,
       0.46109086, 0.46707116, 0.14020141, 0.14730886, 0.64511205])

In [167]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [171]:
import math
math.e
math.pow(math.e,0.29159323)

1.3385584214750086

In [178]:
arr_x = np.array([[1,2,3,4],
                  [5,6,7,8]])
arr_y = np.array([[21,22,23,24],
                  [25,26,27,28]])
arr_x + arr_y
print(np.concatenate((arr_x, arr_y), axis=0))
print(np.concatenate((arr_x, arr_y), axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]
[[ 1  2  3  4 21 22 23 24]
 [ 5  6  7  8 25 26 27 28]]


In [187]:
arr_z = np.concatenate((arr_x, arr_y), axis=0)
print(arr_z)
hsplits = np.hsplit(arr_z, 4)
print(np.array(hsplits))
vsplits = np.vsplit(arr_z,2)
print(np.array(vsplits))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [21 22 23 24]
 [25 26 27 28]]
[[[ 1]
  [ 5]
  [21]
  [25]]

 [[ 2]
  [ 6]
  [22]
  [26]]

 [[ 3]
  [ 7]
  [23]
  [27]]

 [[ 4]
  [ 8]
  [24]
  [28]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[21 22 23 24]
  [25 26 27 28]]]


In [188]:
import numpy as np

countries = ['India', 'France', 'England']
capitals = ['New Delhi', 'Paris', 'London']
arr = np.array(capitals)

In [189]:
import pandas as pd

In [190]:
pd.Series(data = capitals)

0    New Delhi
1        Paris
2       London
dtype: object

In [191]:
pd.Series(data = capitals, index=countries)

India      New Delhi
France         Paris
England       London
dtype: object

In [192]:
pd.Series(arr)

0    New Delhi
1        Paris
2       London
dtype: object

In [193]:
dicts = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80}

pd.Series(dicts)

a    10
b    20
c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64

In [274]:
dicts1 = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70, 'h':80}
dicts2 = {'a':10, 'b':20, 'c':30, 'd':40, 'e':50, 'f':60, 'g':70}
s1 = pd.Series(dicts1)
s2 = pd.Series(dicts2)
s1+s2

a     20.0
b     40.0
c     60.0
d     80.0
e    100.0
f    120.0
g    140.0
h      NaN
dtype: float64

In [194]:
my_series = pd.Series(dicts)

In [195]:
my_series.shape

(8,)

In [196]:
my_series[0]

10

In [197]:
my_series['a']

10

In [198]:
my_series[1:3]

b    20
c    30
dtype: int64

In [200]:
my_series[[True,False,True,False,True,False,True,False]]

a    10
c    30
e    50
g    70
dtype: int64

In [202]:
my_series[['a','c','c']]

a    10
c    30
c    30
dtype: int64

In [203]:
my_series + my_series

a     20
b     40
c     60
d     80
e    100
f    120
g    140
h    160
dtype: int64

In [206]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [207]:
fruits = ['Apple', 'Banana', 'Orange']
fruits_df = pd.DataFrame(data = fruits, columns=['Fruit'])
fruits_df

Fruit
0   Apple
1  Banana
2  Orange

In [208]:
family = [['Suyash', 32, 'Father'],['Abha', 32, 'Mother'],['Atharv', 3, 'Son']]
family_df = pd.DataFrame(data = family, columns=['Name', 'Age', 'Role'])
family_df

Name  Age    Role
0  Suyash   32  Father
1    Abha   32  Mother
2  Atharv    3     Son

In [214]:
family = {'Name':['Suyash', 'Abha', 'Atharv'], 'Age':[32,32,3], 'Role':["Father", "Mother", "Son"]}
family_df = pd.DataFrame(data = family)
family_df

Name  Age    Role
0  Suyash   32  Father
1    Abha   32  Mother
2  Atharv    3     Son

In [215]:
csv_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.csv")
csv_df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [217]:
json_df = pd.read_json("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.json")
json_df

Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
5  551 Alvarado St  San Francisco     USA         20   6   Richvalley   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California  
5          CA 94114

In [218]:
excel_df = pd.read_excel("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/supermarkets.xlsx?raw=true", sheet_name=0)
excel_df

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [114]:
employee_df = pd.read_csv('https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/Employee%20data.csv')

In [115]:
employee_df.head()

Gender  Employee Number           Skills  Total Working Years  \
0  Female                1            Sales                    8   
1  Female                5         Research                    8   
2  Female               10  Content Writing                   12   
3  Female               15  Content Writing                   10   
4  Female               20            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [125]:
employee_df.set_index(["Gender","Skills"]).xs('Sales',level="Skills")

Employee Number  Total Working Years  Work Life Balance  \
Gender                                                            
Female                1                    8                  1   
Female               20                   10                  3   
Female               26                    5                  2   
Female               49                    2                  3   
Female               52                   10                  3   
Female               68                    9                  2   
Female               72                    5                  2   
Female               81                   28                  2   
Female               91                   20                  2   
Female               98                   11                  3   
Female              121                   11                  2   
Female              128                    4                  2   
Female              154                   10                  3   
Female              170                   16                  2   
Female              174                   16                  3   
Female              175                    4                  3   
Female              182                   17                  4   
Female              207                    9                  3   
Female              216                    6                  3   
Female              228                   12                  3   
Female              230                   12                  4   
Female              235                    1                  4   
Female              240                    9                  4   
Female              244                   24                  3   
Female              248                    4                  2   
Female              250                    5                  3   
Female              270                   11                  3   
Female              283                   10                  2   
Male                293                    7                  3   
Male                299                    9                  2   
...                 ...                  ...                ...   
Male               1882                    9                  3   
Male               1908                   12                  1   
Male               1924                   10                  2   
Male               1927                    7                  3   
Male               1928                    1                  3   
Male               1936                   10                  3   
Male               1943                   14                  3   
Male               1945                    6                  1   
Male               1950                   14                  2   
Male               1951                    9                  2   
Male               1961                   20                  2   
Male               1965                    7                  3   
Male               1966                    8                  3   
Male               1967                   10                  3   
Male               1968                   15                  2   
Male               1975                   21                  3   
Male               1995                   16                  3   
Male               1996                    3                  3   
Male               1997                   10                  3   
Male               2013                    3                  3   
Male               2019                   16                  2   
Male               2021                    2                  3   
Male               2023                    1                  2   
Male               2036                   15                  2   
Male               2037                   14                  3   
Male               2044                   12                  3   
Male               2055                   20           

In [41]:
employee_df.loc[0:4, ["Gender","Skills"]]

Gender           Skills
0  Female            Sales
1  Female         Research
2  Female  Content Writing
3  Female  Content Writing
4  Female            Sales

In [37]:
employee_df.iloc[:3,:3]

Gender  Employee Number           Skills
0  Female                1            Sales
1  Female                5         Research
2  Female               10  Content Writing

In [220]:
employee_df.shape

(1470, 9)

In [224]:
employee_df.dtypes

Gender                      object
Employee Number              int64
Skills                      object
Total Working Years          int64
Work Life Balance            int64
Performance Rating           int64
Years At Company             int64
MonthlyIncome(June-2018)     int64
MonthlyIncome(June-2017)     int64
dtype: object

In [225]:
employee_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 9 columns):
Gender                      1470 non-null object
Employee Number             1470 non-null int64
Skills                      1470 non-null object
Total Working Years         1470 non-null int64
Work Life Balance           1470 non-null int64
Performance Rating          1470 non-null int64
Years At Company            1470 non-null int64
MonthlyIncome(June-2018)    1470 non-null int64
MonthlyIncome(June-2017)    1470 non-null int64
dtypes: int64(7), object(2)
memory usage: 103.4+ KB


In [226]:
employee_df.count()

Gender                      1470
Employee Number             1470
Skills                      1470
Total Working Years         1470
Work Life Balance           1470
Performance Rating          1470
Years At Company            1470
MonthlyIncome(June-2018)    1470
MonthlyIncome(June-2017)    1470
dtype: int64

In [230]:
employee_df.index

RangeIndex(start=0, stop=1470, step=1)

In [231]:
employee_df.head()

Gender  Employee Number           Skills  Total Working Years  \
0  Female                1            Sales                    8   
1  Female                5         Research                    8   
2  Female               10  Content Writing                   12   
3  Female               15  Content Writing                   10   
4  Female               20            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [244]:
new_df = employee_df.set_index('Employee Number')

In [250]:
new_df.reset_index(inplace=True)

In [251]:
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  
0                      5993                      5893  
1                      5130                      4000  
2                      2090                      3050  
3                      2909                      5909  
4                      3468                      2468

In [265]:
new_df['Name'] = ['Anonymous' for i in range(new_df.shape[0])]

In [267]:
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)       Name  
0                      5993                      5893  Anonymous  
1                      5130                      4000  Anonymous  
2                      2090                      3050  Anonymous  
3                      2909                      5909  Anonymous  
4                      3468                      2468  Anonymous

In [268]:
new_df['Years Outside Company'] = new_df['Total Working Years'] - new_df['Years At Company']
new_df.head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)       Name  \
0                      5993                      5893  Anonymous   
1                      5130                      4000  Anonymous   
2                      2090                      3050  Anonymous   
3                      2909                      5909  Anonymous   
4                      3468                      2468  Anonymous   

   Years Outside Company  
0                      2  
1                      0  
2                     11  
3                      1  
4                      0

In [270]:
new_df.drop(labels='Name', axis=1).head()

Employee Number  Gender           Skills  Total Working Years  \
0                1  Female            Sales                    8   
1                5  Female         Research                    8   
2               10  Female  Content Writing                   12   
3               15  Female  Content Writing                   10   
4               20  Female            Sales                   10   

   Work Life Balance  Performance Rating  Years At Company  \
0                  1                   3                 6   
1                  3                   3                 8   
2                  2                   4                 1   
3                  3                   3                 9   
4                  3                   2                10   

   MonthlyIncome(June-2018)  MonthlyIncome(June-2017)  Years Outside Company  
0                      5993                      5893                      2  
1                      5130                      4000                      0  
2                      2090                      3050                     11  
3                      2909                      5909                      1  
4                      3468                      2468                      0

In [ ]:
new_df.drop(labels='')

In [271]:
dicts = {1:'Ram', 2:'Shyam', 3:'Ghanshyam'}
mydf = pd.Series(data=dicts)
mydf


1          Ram
2        Shyam
3    Ghanshyam
dtype: object

In [273]:
mydf[1]

'Ram'

In [1]:
import pandas as pd

In [6]:
df = pd.DataFrame(data={"Name":["Suyash", "Abha", "Atharv"], "Age":[32,32,3], "Blood Group":["A+", "B+", "B+"]})
df

Name  Age Blood Group
0  Suyash   32          A+
1    Abha   32          B+
2  Atharv    3          B+

In [27]:
new_df = df.copy()
print(new_df)
new_df.set_index('Name',inplace=True)
print(new_df)
print(new_df.info())
print(new_df.shape)
print(new_df.ndim)
print()
print(df.info())
print(df.shape)
print(df.ndim)

     Name  Age Blood Group
0  Suyash   32          A+
1    Abha   32          B+
2  Atharv    3          B+
        Age Blood Group
Name                   
Suyash   32          A+
Abha     32          B+
Atharv    3          B+
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Suyash to Atharv
Data columns (total 2 columns):
Age            3 non-null int64
Blood Group    3 non-null object
dtypes: int64(1), object(1)
memory usage: 72.0+ bytes
None
(3, 2)
2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name           3 non-null object
Age            3 non-null int64
Blood Group    3 non-null object
dtypes: int64(1), object(2)
memory usage: 152.0+ bytes
None
(3, 3)
2


Name  Age Blood Group
0  Suyash   32          A+
1    Abha   32          B+
2  Atharv    3          B+

In [67]:
df.loc[:,:]

Name  Age Blood Group
0  Suyash   32          A+
1    Abha   32          B+
2  Atharv    3          B+

In [69]:
pd.concat([df,df.iloc[:2,:2]],axis=1).reset_index()

index    Name  Age Blood Group    Name   Age
0      0  Suyash   32          A+  Suyash  32.0
1      1    Abha   32          B+    Abha  32.0
2      2  Atharv    3          B+     NaN   NaN

In [70]:
df2 = pd.DataFrame(data={"Name":["Nani", "Abha", "Atharv"], "Age":[54,32,3], "Blood Group":["B+", "B+", "B+"]})


In [72]:
pd.concat([df,df2],axis=1)

Name  Age Blood Group    Name  Age Blood Group
0  Suyash   32          A+    Nani   54          B+
1    Abha   32          B+    Abha   32          B+
2  Atharv    3          B+  Atharv    3          B+

In [89]:
import numpy as np

In [73]:
employee_df = pd.DataFrame(data={"Id":[1,2,3], "Name":["Ram", "Shyam", "Ghanshyam"]})

In [84]:
employee_df[employee_df["Name"]=="Ram"]

Id Name
0   1  Ram

In [75]:
department_df = pd.DataFrame(data={"Id":[1,2,4,5], "DepartmentName":["HR","Sales","Marketing","IT"]})

In [96]:
pd.merge(left=employee_df,right=department_df,on='Id',how="left")

Id       Name DepartmentName
0   1        Ram             HR
1   2      Shyam          Sales
2   3  Ghanshyam            NaN

In [101]:
us_states = pd.DataFrame(data=[["USA","Ohio","Cincinnati"],["USA","Kentucky","Nashville"]], columns=["Country","State","City"])

In [109]:
india_states = pd.DataFrame(data=[["India","Lucknow","UP"],["India","Bengaluru","Karnataka"]], columns=["Country","City","State"])

In [113]:
us_states.append(india_states)

City Country      State
0  Cincinnati     USA       Ohio
1   Nashville     USA   Kentucky
0     Lucknow   India         UP
1   Bengaluru   India  Karnataka

In [126]:
import seaborn as sns
tips = sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [128]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB


In [129]:
tips.day.unique()

[Sun, Sat, Thur, Fri]
Categories (4, object): [Sun, Sat, Thur, Fri]

In [130]:
tips.time.unique()

[Dinner, Lunch]
Categories (2, object): [Dinner, Lunch]

In [133]:
tips[tips.time == 'Lunch']['tip'].sum()

185.51000000000002

In [134]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [149]:
tips.groupby(by=["sex", "day", "time"])['tip'].agg(["sum","mean","count"]).xs('Fri', level="day")

sum      mean  count
sex    time                          
Male   Lunch    5.70  1.900000      3
       Dinner  21.23  3.032857      7
Female Lunch   10.98  2.745000      4
       Dinner  14.05  2.810000      5

In [153]:
tips.groupby(by=["sex", "day", "time"])['tip'].agg(["sum","mean","count"]).index


MultiIndex(levels=[['Male', 'Female'], ['Thur', 'Fri', 'Sat', 'Sun'], ['Lunch', 'Dinner']],
           labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], [0, 1, 1, 2, 3, 0, 0, 1, 1, 2, 3], [0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1]],
           names=['sex', 'day', 'time'])

In [157]:
tips['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [159]:
tips.groupby(by="time").count()["tip"]

time
Lunch      68
Dinner    176
Name: tip, dtype: int64

In [162]:
tips['size'] = tips['size']*2

In [167]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     4
1       10.34  1.66    Male     No  Sun  Dinner     6
2       21.01  3.50    Male     No  Sun  Dinner     6
3       23.68  3.31    Male     No  Sun  Dinner     4
4       24.59  3.61  Female     No  Sun  Dinner     8

In [173]:
tips.groupby(by="sex")['tip'].agg(["sum", "mean"]).loc[:,["sum"]]

sum
sex           
Male    485.07
Female  246.51

In [2]:
import pandas as pd

In [3]:
air_df = pd.read_csv("https://raw.githubusercontent.com/insaid2018/Term-1/master/Data/Casestudy/AirQualityUCI.csv")

In [4]:
air_df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0  3/10/2004  18:00:00     2.6         1360       150      11.9   
1  3/10/2004  19:00:00     2.0         1292       112       9.4   
2  3/10/2004  20:00:00     2.2         1402        88       9.0   
3  3/10/2004  21:00:00     2.2         1376        80       9.2   
4  3/10/2004  22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [5]:
air_df.Date = pd.to_datetime(air_df.Date, format='%m/%d/%Y')

In [6]:
air_df.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0 2004-03-10  18:00:00     2.6         1360       150      11.9   
1 2004-03-10  19:00:00     2.0         1292       112       9.4   
2 2004-03-10  20:00:00     2.2         1402        88       9.0   
3 2004-03-10  21:00:00     2.2         1376        80       9.2   
4 2004-03-10  22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [7]:
air_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
Date             9357 non-null datetime64[ns]
Time             9357 non-null object
CO(GT)           9357 non-null float64
PT08.S1(CO)      9357 non-null int64
NMHC(GT)         9357 non-null int64
C6H6(GT)         9357 non-null float64
PT08.S2(NMHC)    9357 non-null int64
NOx(GT)          9357 non-null int64
PT08.S3(NOx)     9357 non-null int64
NO2(GT)          9357 non-null int64
PT08.S4(NO2)     9357 non-null int64
PT08.S5(O3)      9357 non-null int64
T                9357 non-null float64
RH               9357 non-null float64
AH               9357 non-null float64
dtypes: datetime64[ns](1), float64(5), int64(8), object(1)
memory usage: 1.1+ MB


In [8]:
air_df.Time = pd.to_datetime(air_df.Time, format='%H:%M:%S')

In [9]:
air_df.head()

Date                Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0 2004-03-10 1900-01-01 18:00:00     2.6         1360       150      11.9   
1 2004-03-10 1900-01-01 19:00:00     2.0         1292       112       9.4   
2 2004-03-10 1900-01-01 20:00:00     2.2         1402        88       9.0   
3 2004-03-10 1900-01-01 21:00:00     2.2         1376        80       9.2   
4 2004-03-10 1900-01-01 22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [15]:
air_df.Date.dt.year

0       2004
1       2004
2       2004
3       2004
4       2004
5       2004
6       2004
7       2004
8       2004
9       2004
10      2004
11      2004
12      2004
13      2004
14      2004
15      2004
16      2004
17      2004
18      2004
19      2004
20      2004
21      2004
22      2004
23      2004
24      2004
25      2004
26      2004
27      2004
28      2004
29      2004
        ... 
9327    2005
9328    2005
9329    2005
9330    2005
9331    2005
9332    2005
9333    2005
9334    2005
9335    2005
9336    2005
9337    2005
9338    2005
9339    2005
9340    2005
9341    2005
9342    2005
9343    2005
9344    2005
9345    2005
9346    2005
9347    2005
9348    2005
9349    2005
9350    2005
9351    2005
9352    2005
9353    2005
9354    2005
9355    2005
9356    2005
Name: Date, Length: 9357, dtype: int64

In [16]:
date_series = air_df.Date

In [17]:
date_series_dt = date_series.dt

In [19]:
%config IPCompleter.greedy=True


In [20]:
get_ipython().Completer.greedy

True

In [22]:
dt_series = air_df.Date.dt

In [23]:
air_df.head()

Date                Time  CO(GT)  PT08.S1(CO)  NMHC(GT)  C6H6(GT)  \
0 2004-03-10 1900-01-01 18:00:00     2.6         1360       150      11.9   
1 2004-03-10 1900-01-01 19:00:00     2.0         1292       112       9.4   
2 2004-03-10 1900-01-01 20:00:00     2.2         1402        88       9.0   
3 2004-03-10 1900-01-01 21:00:00     2.2         1376        80       9.2   
4 2004-03-10 1900-01-01 22:00:00     1.6         1272        51       6.5   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0           1046      166          1056      113          1692         1268   
1            955      103          1174       92          1559          972   
2            939      131          1140      114          1555         1074   
3            948      172          1092      122          1584         1203   
4            836      131          1205      116          1490         1110   

      T    RH      AH  
0  13.6  48.9  0.7578  
1  13.3  47.7  0.7255  
2  11.9  54.0  0.7502  
3  11.0  60.0  0.7867  
4  11.2  59.6  0.7888

In [30]:
foo = air_df[air_df['Time'] < pd.to_datetime('09:00:00', format='%H:%M:%S')]['Time']
print(foo.max())
print(foo.min())

1900-01-01 08:00:00
1900-01-01 00:00:00


In [31]:
dateStamp = pd.to_datetime('04/29/2013', format="%m/%d/%Y")

In [34]:
from datetime import timedelta

In [36]:
foo = dateStamp + timedelta(days=1)

In [37]:
type(foo)

pandas._libs.tslibs.timestamps.Timestamp